config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users
  resources :patients
  
  resources :doctors do
    resources :clinics
    resources :schedules
  end

  get '/profile/:id', to: 'doctors#profile', as: 'profile'
  get 'home/index'
  get 'patient_list', to: 'patients#patient_list'
  get 'clinics/get_clinic_variable'
  
  match '*path' => 'application#error_404', via: :all
end

app/models/patient.rb
class Patient < ApplicationRecord
  
  validates_presence_of :first_name, :last_name, :address, :city, :state, :phone_no,
                        :pincode, :age, :sex
  belongs_to :user
  has_many :bookings, dependent: :destroy

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user
  before_action :set_patient, only: [:edit, :update, :show, :destroy]
  
  def index
    @schedules = Schedule.all
    #authorize Patient
  end

  def patient_list
    @patients = Patient.all
  end

  def show
    authorize @patient
  end

  def new
    @patient = Patient.new
    authorize @patient
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.user = current_user
    @patient.save
    flash[:notice] = 'Create succesfully!'
    redirect_to doctors_path
  end

  def edit
    authorize @patient
  end

  def update
    authorize @patient
    if @patient.update(patient_params)
      flash[:notice] = 'Edit successfully!'
      redirect_to @patient
    else
      flash[:danger] = 'Something went wrong!'
      render 'edit'
    end
  end

  def destroy
    authorize @patient
    @patient.destroy
    flash[:danger] = 'Delete successfully!'
    redirect_to patients_path
  end

  private
  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :age, :sex, :address, :city, :state, :phone_no, :pincode)
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

end

app/views/patients/_form.html.erb
<%= form_with model: @patient, local: true do |f| %>
  <div class="modal-body">
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :age %><br>
        <%= f.number_field :age, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :sex %><br>
        <%= f.text_field :sex, class: "form-control" %>
      </div>
    </div>
    </div>
    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :city %><br>
        <%= f.text_field :city, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :state %><br>
        <%= f.text_field :state, class: "form-control" %>
      </div>
    </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :phone_no %><br>
        <%= f.text_field :phone_no, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :pincode %><br>
        <%= f.text_field :pincode, class: "form-control" %>
      </div>
    </div>
    </div>
  <div class="modal-footer border-top-0 d-flex justify-content-center">
    <%= f.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<div class="container patients shadow-lg p-3 mb-5 bg-white rounded">
    <h1 class="form-title"> Edit patient details </h1><hr>
    <%= render 'form' %>
</div>

app/views/patients/index.html.erb
<% if !Schedule.exists?(patient_id: Patient.find_by_user_id(current_user)) %>
  <div class="container patients">
    <div class="jumbotron jumbo-p">
      <h4> Looks like you haven't any appointment! </h4><hr>
      <%= image_tag "schedule.svg", class: "schedule_img "%>
      <% if !Patient.find_by_user_id(current_user) %>
        <%= link_to 'Book an appointment', new_patient_path, class: "btn btn-info" %>
      <% else %>
        <%= link_to 'Book an appointment', doctors_path, class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="container">
    <% @schedules.each do |schedule| %>
    <% if schedule.patient_id == find_user.id %>
      <div class="row row-striped">
        <div class="col-2 text-right">
          <h1 class="display-4"><span class="badge badge-secondary"><%= schedule.start.strftime("%d") %></span></h1>
          <h2 class="month_schedule"><%= schedule.start.strftime("%b") %></h2>
        </div>
        <div class="col-7">
          <h3 class="text-uppercase"><strong>Appointment</strong></h3>
          <ul class="list-inline">
              <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> <%= schedule.start.strftime("%A") %></li>
            <li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i> <%= schedule.start.strftime("%I:%M%p") %> - <%= schedule.end.strftime("%I:%M%p") %></li>
            <li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i> Cafe</li>
          </ul>
          <p>Please available an hour before your schedule time</p>
        </div>
        <div class="col-3">
          <ul class="list-unstyled">
            <li class="list-item"><i class="fa fa-bell-o fa-2x" aria-hidden="true"></i> Status </li>
            <li class="list-item"><i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i> Edit </li>
            <li class="list-item"><i class="fa fa-trash fa-2x" aria-hidden="true"></i> Cancel </li>
          </ul>
        </div>
      </div>
      <% end %>
    <% end %>
    <%= link_to 'Book an appointment', doctors_path, class: "btn btn-info btn-schedule" %>
	</div>
<% end %>

app/views/patients/new.html.erb
<div class="container patients">
  <div class="jumbotron">
    <h4 class="form-title"><b>Fill the form</b></h4>
      <%= form_with model: @patient do |f| %>
        <div class="modal-body">
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :first_name %><br>
              <%= f.text_field :first_name, class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :last_name %><br>
              <%= f.text_field :last_name, class: "form-control" %>
            </div>
          </div>
          </div>
          <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :age %><br>
              <%= f.number_field :age, class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :sex %><br>
              <%= f.text_field :sex, class: "form-control" %>
            </div>
          </div>
          </div>
          <div class="form-group">
            <%= f.label :address %><br>
            <%= f.text_field :address, class: "form-control" %>
          </div>
          <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :city %><br>
              <%= f.text_field :city, class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :state %><br>
              <%= f.text_field :state, class: "form-control" %>
            </div>
          </div>
          </div>
          <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :phone_no %><br>
              <%= f.text_field :phone_no, class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :pincode %><br>
              <%= f.text_field :pincode, class: "form-control" %>
            </div>
          </div>
          </div>
        <div class="modal-footer border-top-0 d-flex justify-content-center">
          <%= f.submit "Submit", class: "btn btn-success" %>
        </div>
      <% end %>
    
  </div>
</div>

app/views/patients/patient_list.html.erb
<div class="container doctor">
  <div class="jumbotron">
    <h1> patients List </h1>
      <div class="row">
        <div class="col-md-12">
        <div class="table-responsive">
          <table id="mytable" class="table table-bordred table-striped">
            <thead>
              <th> Name </th>
              <th> Sex </th>
              <th> Age </th>
              <th> Show </th>
            </thead>
            <tbody>
              <% @patients.each do |patient| %>
                <tr>
                  <td><%= patient.first_name %></td>
                  <td><%= patient.sex %></td>
                  <td><%= patient.age %></td>
                  <td><%= link_to 'Details', patient_path(patient), :class => "btn btn-success" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
            <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1"><i class="fa fa-arrow-left"></i></a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
              <a class="page-link" href="#"><i class="fa fa-arrow-right"></i></a>
              </li>
            </ul>
          </nav>
        </div>
        </div>
      </div>
  </div>
</div>

app/views/patients/show.html.erb
<div class="container patients shadow-lg p-3 mb-5 bg-white rounded">
  <h1 class="form-title"> Patient details </h1><hr>
  <ul class="list-group">
    <li class="list-group-item text-muted" contenteditable="false">Profile</li>
    <% fname = @patient.first_name %>
    <% lname = @patient.last_name %>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Name: </strong></span> <%= fname + " " + lname %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Age: </strong></span><%= @patient.age %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Sex: </strong></span><%= @patient.sex %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Address: </strong></span><%= @patient.address %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">City: </strong></span><%= @patient.city %> </li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">State: </strong></span><%= @patient.state %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Pincode: </strong></span><%= @patient.pincode %></li>  
    <li class="list-group-item text-muted" contenteditable="false">Contact Details</li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Phone Number: </strong></span><%= @patient.phone_no %></li>                
  </ul>
  <div class="modal-footer border-top-0 d-flex justify-content-left">
  <% if !current_user.admin? %>
    <%= link_to 'Edit', edit_patient_path(@patient), class: "btn btn-info" %>
    <%= link_to 'Delete', patient_path(@patient), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% else %>
    <%= link_to 'Delete', patient_path(@patient), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% end %>
  </div>
</div>