config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users
  resources :patients
  
  resources :doctors do
    resources :clinics
    resources :schedules
  end

  get '/profile/:id', to: 'doctors#profile', as: 'profile'
  get 'home/index'
  get 'patient_list', to: 'patients#patient_list'
  get 'clinics/get_clinic_variable'
  
  match '*path' => 'application#error_404', via: :all
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  
  validates :user_id, uniqueness: true
  validates_presence_of :first_name, :last_name, :address, :city, :state, :country,
                        :pincode, :dob
  belongs_to :user
  belongs_to :category
  has_many :clinics, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_many :bookings, dependent: :destroy
  before_save :downcase_name

  def self.search(search)
    if search
      where(["first_name LIKE ?","%#{search}%"])
    else
      all
    end

  end

  def downcase_name
    self.first_name.downcase!
    self.last_name.downcase!
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user
  before_action :get_id, only: [:edit, :update, :show, :profile, :destroy]

  def index
    @doctors = Doctor.search(params[:search])
  end

  def show
    authorize @doctor
    #@clinics = @doctor.clinics
    @today_schedules = Schedule.where("DATE(start) = DATE(?)", Date.today)
    @future_schedules = Schedule.where("DATE(start) > DATE(?)", Date.today)
    @past_schedules = Schedule.where("DATE(start) < DATE(?)", Date.today)
  end

  def profile
    authorize @doctor
  end
  
  def new
    @doctor = Doctor.new
    authorize @doctor
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.user = current_user
    @doctor.save
    authorize @doctor
    flash[:notice] = 'Create succesfully!'
    redirect_to @doctor
  end

  def edit
    authorize @doctor
  end

  def update
    authorize @doctor
    if @doctor.update(doctor_params)
      flash[:notice] = 'Edit successfully!'
      redirect_to @doctor
    else
      flash[:danger] = 'Something went wrong!'
      render 'edit'
    end
  end

  def destroy
    authorize @doctor
    @doctor.destroy
    flash[:danger] = 'Delete successfully!'
    redirect_to root_path
  end

  private
  
  def get_id
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :dob, :address, :city, :state, :country, :pincode, :category_id)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with model: @doctor do |f| %>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :first_name %><br>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :last_name %><br>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-12">
        <div class="form-group">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :dob %><br>
          <%= f.date_field :dob, :value => Time.now.strftime('%Y-%m-%d'), class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :Specialization %><br>
          <%= f.collection_select :category_id, Category.order(:category_name), :id, :category_name, {include_blank: false}, { class: 'form-control'} %>
        </div>
      </div>
      
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :city %><br>
          <%= f.text_field :city, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :state %><br>
          <%= f.text_field :state, class: "form-control" %>
        </div>
      </div>
                
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :country %><br>
          <%= f.text_field :country, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :pincode %><br>
          <%= f.number_field :pincode, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <br>
          <%= f.submit "Submit", class: "btn btn-success" %>
          <button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button>
        </div>
      </div>
    </div>
  <% end %>

app/views/doctors/_modal.html.erb
<div class="modal fade" id="newEvent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Booking Confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure want to book an appointment?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-primary" id="submit">Yes</button>
      </div>
    </div>
  </div>
</div>

app/views/doctors/_table.html.erb
<table id="mytable" class="table table-striped">
  <thead>
    <th>Name</th>
    <th>Age</th>
    <th>sex</th>
    <th>Address</th>
    <th>Time</th>
    <th>Delete</th>
  </thead>
  <tbody>
    <% patient = Patient.find(schedule.patient_id) %>
    <tr>
    <td><%= patient.first_name + " " + patient.last_name %></td>
    <td><%= patient.age %></td>
    <td><%= patient.sex %></td>
    <td><%= patient.address %></td>
    <td><%= schedule.start.strftime("%H:%M:%S %a") %>
    <td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><i class="fa fa-trash"></i></button></p></td>
    </tr>
  </tbody>
</table>

app/views/doctors/edit.html.erb
<div class="container doctors shadow-lg p-3 mb-5 bg-white rounded">
  <h1> Edit profile </h1><hr>
  <%= render 'doctors/form' %>
  <div class="modal-footer border-top-0 d-flex justify-content-left">
    <%= link_to 'Back', doctor_path(@doctor), class: "btn btn-info" %>
  </div>
</div>

app/views/doctors/index.html.erb
<div class="row mt-5">
  <div class="col-md-12">
    <%= form_tag doctors_path, :method => 'get', :class => "form-inline active-cyan-4 index-form" do %>
      <%= text_field_tag :search, params[:search], :class => "form-control form-control-sm mr-3 index-search", :placeholder => "Enter name of doctor for search" %>
      <%= button_tag(type: "submit", class: "btn btn-default p-0") do %>
        <i class="fa fa-search fa-2x "></i>
      <% end %>
    <% end %>
  </div>
</div>


<div class="container doctor">
  <div class="jumbotron">
    <h1> Doctors List </h1>
      <div class="row">
        <div class="col-md-12">
        <div class="table-responsive">
          <table id="mytable" class="table table-bordred table-striped">
            <thead>
              <th> Name </th>
              <th> Specialization </th>
              <th> city </th>
              <% if !current_user.admin? %>
                <th> Appointment </th>
              <% else %>
                <th> Details </th>
              <% end %>
            </thead>
            <tbody>
              <% @doctors.each do |doctor| %>
                <tr>
                  <td><%= doctor.first_name.capitalize! %></td>
                  <td><%= Category.find(doctor.category_id).category_name %></td>
                  <td><%= doctor.city %></td>
                  <td><% if !current_user.admin? %>
                      <%= link_to 'book', doctor_path(doctor), :class => "btn btn-success" %>
                      <% else %>
                      <%= link_to 'show', profile_path(doctor), :class => "btn btn-success" %>
                      <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
            <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1"><i class="fa fa-arrow-left"></i></a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
              <a class="page-link" href="#"><i class="fa fa-arrow-right"></i></a>
              </li>
            </ul>
          </nav>
        </div>
        </div>
      </div>
  </div>
</div>

app/views/doctors/new.html.erb
<div class="container doctors shadow-lg p-3 mb-5 bg-white rounded">
  <h1> Profile </h1><hr>
  <%= form_with model: @doctor do |f| %>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :first_name %><br>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :last_name %><br>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-12">
        <div class="form-group">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :dob %><br>
          <%= f.date_field :dob, :value => Time.now.strftime('%Y-%m-%d'), class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :Specialization %><br>
          <%= f.collection_select :category_id, Category.order(:category_name), :id, :category_name, {include_blank: false}, { class: 'form-control'} %>
        </div>
      </div>
      
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :city %><br>
          <%= f.text_field :city, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :state %><br>
          <%= f.text_field :state, class: "form-control" %>
        </div>
      </div>
                
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :country %><br>
          <%= f.text_field :country, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :pincode %><br>
          <%= f.number_field :pincode, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <br>
          <%= f.submit "Submit", class: "btn btn-success" %>
          <button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/doctors/profile.html.erb
<div class="container patients shadow-lg p-3 mb-5 bg-white rounded">
  <h1 class="form-title"> Personal details </h1><hr>
  <ul class="list-group">
    <li class="list-group-item text-muted" contenteditable="false">Profile</li>
    <% fname = @doctor.first_name.capitalize! %>
    <% lname = @doctor.last_name %>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Name: </strong></span> <%= fname + " " + lname %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Category: </strong></span><%= category_id.category_name %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">DOB: </strong></span><%= @doctor.dob %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Address: </strong></span><%= @doctor.address %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">City: </strong></span><%= @doctor.city %> </li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">State: </strong></span><%= @doctor.state %></li>
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Country: </strong></span><%= @doctor.country %></li>  
    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Pin code: </strong></span><%= @doctor.pincode %></li>                
  </ul>
  <div class="modal-footer border-top-0 d-flex justify-content-left">
    <% if !current_user.admin? %>
      <%= link_to 'Add Clinic', new_doctor_clinic_path(@doctor), class: "btn btn-success" %>
      <%= link_to 'Edit', edit_doctor_path(@doctor), class: "btn btn-info" %>
      <%= link_to 'Delete', doctor_path(@doctor), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <% else %>
      <%= link_to 'Show clinic', doctor_clinic_path(@doctor), class: "btn btn-success" %>
      <%= link_to 'Delete', doctor_path(@doctor), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/doctors/show.html.erb
<div class="container content shadow-lg p-3 mb-5 bg-white rounded">
    <div class="row profile">
      <div class="col-md-3 border-right">
        <div class="profile-sidebar">
          <!-- SIDEBAR USERPIC -->
          <div class="profile-userpic">
            <img src="https://media.rockstargames.com/chinatownwars/global/downloads/avatars/zhou_256x256.jpg" class="img-responsive" alt="">
          </div>
          <!-- END SIDEBAR USERPIC -->
          <!-- SIDEBAR USER TITLE -->
          <div class="profile-usertitle">
            <div class="profile-usertitle-name">
              <% fname = @doctor.first_name.capitalize! %>
              <% lname = @doctor.last_name %>
              <%= fname + " " + lname %>
            </div>
            <div class="profile-usertitle-job">
              <%= Category.find(@doctor.category_id).category_name %>
            </div>
            <div class="appointment">
              Appointment
            </div>
          </div>
          <!-- END SIDEBAR USER TITLE -->
          <!-- SIDEBAR BUTTONS -->
          <div class="profile-userbuttons">
            <button type="button" class="btn btn-success btn-sm">Current</button>
            <button type="button" class="btn btn-danger btn-sm">Future</button>
          </div>
          <!-- END SIDEBAR BUTTONS -->
          <!-- SIDEBAR MENU -->
          <div class="profile-usermenu sidebar-sticky">
            <ul class="nav flex-column">
                <li class="list-group-item text-center"><span class="pull-left"><strong class=""></strong></span> <%= @doctor.address %></li>
                <li class="list-group-item text-center"><span class="pull-left"><strong class=""></strong></span><%= @doctor.city %>, <%= @doctor.state %> </li>
                <% if clinic_id %>
                <li class="list-group-item text-left text-muted" contenteditable="false">Clinic Details:</li>
                <li class="list-group-item text-center"><span class="pull-left"><strong class=""></strong></span><%= clinic_id.clinic_address %>, <%= clinic_id.city %>, <%= clinic_id.state %> </li>
                <li class="list-group-item text-center"><span class="pull-left"><strong class=""></strong></span><%= clinic_id.phone_no %></li>
                <% end %>
                <li class="list-group-item text-left text-muted" contenteditable="false">Contact Details:</li>
                <li class="list-group-item text-center"><span class="pull-left"><strong class=""></strong></span><%= User.find(@doctor.user_id).email %> </li>
                <li class="list-group-item text-center"><span class="pull-left"><strong class=""></strong></span>09159092245</li>
            </ul>
          </div>
          <!-- END MENU -->
        </div>
      </div>
      <div class="col-md-9 ">
        <nav>
          <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
          <% if current_user.role === "patient" %>
            <a class="nav-item nav-link active" id="nav-schedule-tab" data-toggle="tab" href="#nav-schedule" role="tab" aria-controls="nav-schedule" aria-selected="true">Schedule</a>
          <% else %>
            <a class="nav-item nav-link active" id="nav-schedule-tab" data-toggle="tab" href="#nav-schedule" role="tab" aria-controls="nav-schedule" aria-selected="true">Schedule</a>
            <a class="nav-item nav-link" id="nav-today-list-tab" data-toggle="tab" href="#nav-today-list" role="tab" aria-controls="nav-today-list" aria-selected="false">Today's List</a>
            <a class="nav-item nav-link" id="nav-future-list-tab" data-toggle="tab" href="#nav-future-list" role="tab" aria-controls="nav-future-list" aria-selected="false">Future List</a>
            <a class="nav-item nav-link" id="nav-about-tab" data-toggle="tab" href="#nav-about" role="tab" aria-controls="nav-about" aria-selected="false">Past List</a>
          <% end %>
          </div>
        </nav>
          <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-schedule" role="tabpanel" aria-labelledby="nav-schedule-tab">
              <div class="instruction">
              <ul>
                <li> For booking please choose your preferred date and time slot </li>
                <li> Grey slot - Past booked appointment </li>
                <li> Red slot - Today's booked appointment </li>
                <li> Green slot - Future booked appointment </li>
              </ul> 
              </div>
              <div id='calendar'></div>
            </div>
            <div class="tab-pane fade" id="nav-today-list" role="tabpanel" aria-labelledby="nav-today-list-tab">
            <% @today_schedules.each do |schedule| %>
              <%= render partial: "table", locals: {schedule: schedule} %>
            <% end %>
            </div>
            <div class="tab-pane fade" id="nav-future-list" role="tabpanel" aria-labelledby="nav-future-list-tab">
            <% @future_schedules.each do |schedule| %>
              <%= render partial: "table", locals: {schedule: schedule} %>
            <% end %>
            </div>
            <div class="tab-pane fade" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">
              <% @past_schedules.each do |schedule| %>
              <%= render partial: "table", locals: {schedule: schedule} %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= render 'schedules/new' %>