config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users
  resources :patients
  
  resources :doctors do
    resources :clinics
    resources :schedules
  end

  get '/profile/:id', to: 'doctors#profile', as: 'profile'
  get 'home/index'
  get 'patient_list', to: 'patients#patient_list'
  get 'clinics/get_clinic_variable'
  
  match '*path' => 'application#error_404', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :schedule
  belongs_to :doctor
  belongs_to :patient
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :doctors
end

app/models/clinic.rb
class Clinic < ApplicationRecord
  
  validates_presence_of :start, :end, :clinic_address, :phone_no, :city, :state
  belongs_to :doctor

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  
  validates :user_id, uniqueness: true
  validates_presence_of :first_name, :last_name, :address, :city, :state, :country,
                        :pincode, :dob
  belongs_to :user
  belongs_to :category
  has_many :clinics, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_many :bookings, dependent: :destroy
  before_save :downcase_name

  def self.search(search)
    if search
      where(["first_name LIKE ?","%#{search}%"])
    else
      all
    end

  end

  def downcase_name
    self.first_name.downcase!
    self.last_name.downcase!
  end

end

app/models/patient.rb
class Patient < ApplicationRecord
  
  validates_presence_of :first_name, :last_name, :address, :city, :state, :phone_no,
                        :pincode, :age, :sex
  belongs_to :user
  has_many :bookings, dependent: :destroy

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  
  #validates_presence_of :start, :end
  belongs_to :doctor
  has_many :bookings

end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:patient, :doctor, :admin]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :patient
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :doctors, dependent: :destroy
  has_many :patients, dependent: :destroy
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_doctor_id
  before_action :get_clinic_id, only: [:edit, :update, :show, :profile, :destroy]

  def index
    @clinics = @doctor.clinics
  end

  def show
  end

  def new
    @clinic = Clinic.new
  end

  def create
    @clinic = Clinic.new(clinic_params)
    @clinic.doctor_id = @doctor.id
    @clinic.save
    flash[:notice] = 'Create succesfully!'
    redirect_to doctor_path(@doctor)
  end

  def edit
  end

  def update
    if @clinic.update(clinic_params)
      flash[:notice] = 'Edit successfully!'
      redirect_to doctor_clinics_path
    else
      flash[:danger] = 'Something went wrong!'
      render 'edit'
    end
  end

  def destroy
    @clinic.destroy
    flash[:danger] = 'Delete successfully!'
    redirect_to doctor_path(@doctor)
  end

  def get_clinic_variable
    render json: {  clinics: Clinic.all }
  end

  private

  def clinic_params
    params.require(:clinic).permit(:clinic_address, :city, :state, :phone_no, :start, :end)
  end

  def get_clinic_id
    @clinic = Clinic.find(params[:id])
  end

  def get_doctor_id
    @doctor = Doctor.find(params[:doctor_id])
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user
  before_action :get_id, only: [:edit, :update, :show, :profile, :destroy]

  def index
    @doctors = Doctor.search(params[:search])
  end

  def show
    authorize @doctor
    #@clinics = @doctor.clinics
    @today_schedules = Schedule.where("DATE(start) = DATE(?)", Date.today)
    @future_schedules = Schedule.where("DATE(start) > DATE(?)", Date.today)
    @past_schedules = Schedule.where("DATE(start) < DATE(?)", Date.today)
  end

  def profile
    authorize @doctor
  end
  
  def new
    @doctor = Doctor.new
    authorize @doctor
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.user = current_user
    @doctor.save
    authorize @doctor
    flash[:notice] = 'Create succesfully!'
    redirect_to @doctor
  end

  def edit
    authorize @doctor
  end

  def update
    authorize @doctor
    if @doctor.update(doctor_params)
      flash[:notice] = 'Edit successfully!'
      redirect_to @doctor
    else
      flash[:danger] = 'Something went wrong!'
      render 'edit'
    end
  end

  def destroy
    authorize @doctor
    @doctor.destroy
    flash[:danger] = 'Delete successfully!'
    redirect_to root_path
  end

  private
  
  def get_id
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :dob, :address, :city, :state, :country, :pincode, :category_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user
  before_action :set_patient, only: [:edit, :update, :show, :destroy]
  
  def index
    @schedules = Schedule.all
    #authorize Patient
  end

  def patient_list
    @patients = Patient.all
  end

  def show
    authorize @patient
  end

  def new
    @patient = Patient.new
    authorize @patient
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.user = current_user
    @patient.save
    flash[:notice] = 'Create succesfully!'
    redirect_to doctors_path
  end

  def edit
    authorize @patient
  end

  def update
    authorize @patient
    if @patient.update(patient_params)
      flash[:notice] = 'Edit successfully!'
      redirect_to @patient
    else
      flash[:danger] = 'Something went wrong!'
      render 'edit'
    end
  end

  def destroy
    authorize @patient
    @patient.destroy
    flash[:danger] = 'Delete successfully!'
    redirect_to patients_path
  end

  private
  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :age, :sex, :address, :city, :state, :phone_no, :pincode)
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :current_user
  before_action :get_schedule, only: [:show, :edit, :update, :destroy]

  def index
    @schedules = Schedule.where(start: params[:start]..params[:end])
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @doctor = Doctor.find(params[:doctor_id])
    @schedule = Schedule.new(schedule_params)
    @schedule.patient_id = (Patient.find_by_user_id(current_user)).id
    @schedule.doctor_id = @doctor.id
    @schedule.save
    flash[:danger] = 'Appointment booked successfully!'
  end

  def destroy
    @schedule.destroy
    flash[:danger] = 'Cancel successfully!'
  end

  private
  def get_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.permit(:start, :end)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :get_user_id, only: [:edit, :update, :show, :destroy]
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    authorize @user
  end

  def update
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def get_user_id
    @user = User.find(params[:id])
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def find_user
    present_user = Doctor.find_by_user_id(current_user) || Patient.find_by_user_id(current_user)
  end
  
end

app/helpers/category_helper.rb
module CategoryHelper

  def category_id
    category = Category.find(@doctor.category_id)
  end
  
end

app/helpers/clinics_helper.rb
module ClinicsHelper

  def clinic_id
    clinic = Clinic.find_by_doctor_id(@doctor)
  end
  
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">Doc.App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <% if current_user.admin? %>
      <li class="nav-item active">
        <%= link_to "Home", users_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "patient", patient_list_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Doctor", doctors_path, :class => "nav-link" %>
      </li>
    <% elsif current_user.patient? %>
      <li class="nav-item active">
        <%= link_to "Home", patients_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <% if find_user %>
          <%= link_to "About", patient_path(find_user), :class => "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "Setting", "#", :class => "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item active">
        <%= link_to "Home", doctor_path(find_user), :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", profile_path(find_user), :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <div class="dropdown show">
          <%= link_to "Setting", "#",{ 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false", 'class' => "nav-link dropdown-toggle"} %>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <%= link_to "Clinic", doctor_clinics_path(find_user), :class => "dropdown-item" %>
            <a class="dropdown-item" href="#">Other option</a>
            <a class="dropdown-item" href="#">Other option</a>
          </div>
        </div>
      </li>
    <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav">
      <li class="nav-item">
        <% if !find_user %>
          <%= link_to "Doctor?", new_doctor_path, :class => "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to '<i class="fa fa-sign-out"></i>SignOut'.html_safe, destroy_user_session_path, method: :delete, :class => "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsAppointment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" id="bootstrap-css">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  
    <link href='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css' rel='stylesheet' />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js'></script>
  
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.1/fullcalendar.min.js'></script>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.1/fullcalendar.min.css' rel='stylesheet' />



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
    <%= render 'layouts/navbar' %>
  <% end %>
  <% if notice %>
  <div class="alert alert-success alert-dismissible center">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= notice %>
  </div>
  <% end %>
  <% if alert %>
  <div class="alert alert-danger alert-dismissible center">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= alert %>
  </div>
  <% end %>
    <%= yield %>
  </body>
</html>